---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcs-trigger
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcs-trigger
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcs-trigger
subjects:
  - kind: ServiceAccount
    name: vcs-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcs-trigger
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  params:
    - name: source-repo
      description: Source code repository
    - name: sha
      description: Precise SHA of the commit to build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cicd-pipeline-
      spec:
        pipelineRef:
          name: cicd-build-package-deploy
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: nextjsapp-rs
          #- name: source-repo
          #  value: https://github.com/cloud-native-garage-method-cohort/express-demo-rs-ds
          - name: source-repo
            value: $(tt.params.source-repo) # use value from trigger event -- WARNING SECURITY ?
          - name: sha # introduce new param
            value: $(tt.params.sha) # use value from trigger event
          - name: image-repo
            value: quay.io/remiserra/nextjsapp-rs
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: production-repository
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger
spec:
  params:
    - name: source-repo
      value: $(body.repository.url)
    - name: sha
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: vcs-trigger
      template:
        name: vcs-trigger
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vcs-trigger
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-vcs-trigger
    weight: 100
